# Generated by Django 5.2.1 on 2025-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default='updloads/no_image.png', upload_to='uploads'),
        ),
    ]
