# Generated by Django 5.2.1 on 2025-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default='uploads/no_image.png', upload_to='uploads'),
        ),
    ]
